### ISSUE TITLE
`getEvents` should still return a cursor if there are no events

### ISSUE THREAD

**Issue by kalepail** [stellar/stellar-rpc#340]
**Describe the bug**
When `getEvents` doesn't return any events, there is no cursor to paginate on.

> But what if there are no events for a given filter? You may want to continue on but can't because there's no cursor. Especially given the way I think events are retrieved it's quite possible events are "missing" from your query and you need to paginate further for them.

**Comment by Shaptic** [comment]
Oh, I'm a fool. We actually have `cursor` at the top level now rather than per-event. It's the API schema in the SDK that's wrong 🤦 fixed in https://github.com/stellar/js-stellar-sdk/pull/1124, so closing this. Sorry for the confusion!

**Comment by kalepail** [comment]
fwiw there's a cursor at the top level AND per event from the RPC
