### ISSUE TITLE
alert on slack for CI failures after merge to main

### ISSUE THREAD

**Issue by mollykarcher** [stellar/stellar-rpc#86]
### What problem does your feature solve?

Both e2e test runs and dry-runs can fail after PRs get merged to main. It's easy to ignore these failures, and then they can stack up over time, making the release particularly difficult.

### What would you like to see?

All CI failures on `main` should post back to slack. It probably makes sense to have a new channel for this, but we could reuse some existing platform alerting channels if we want.

### What alternatives are there?

- Block PRs/merges on e2e failures instead
- Run e2e tests periodically, rather than on PRs or merges (https://github.com/stellar/system-test/issues/10)

**Comment by psheth9** [comment]
Request submitted to use Actioner app [here](https://stellarfoundation.slack.com/apps/A02TCGS98DS-actioner?tab=more_info) which helps with surfacing any kind of status from Github workflow to Slack
